### PR TITLE
feat(uppercase) Be able to choose number of uppercase letters

### PR DESCRIPTION
**Pull request by holyhope**
Some software have checks for number of upper/lower letters.
This Pull Request let users choose the number of upper letters.

### CODE REVIEW

**Review by ricoleabricot — APPROVED** [review]

**Comment by sethvargo** [comment]
Hi @holyhope thank you for the Pull Request. This feels pretty specific and also changes our public API, so I'm not sure we'll be able to accept this contribution as-is. Can you tell me more about the use case?

**Comment by holyhope** [comment]
Hello @sethvargo,

## About the public API

IMO updating the public API was pretty much nice since it goes in the same direction that how it was already implemented. I mean it seems normal to have the expected number of upper letters when the feature to have expected digits and specials characters count is already available.
But if you want, I can move it to a `/v2` folder to have a transition time of the public API?

## Use case

I am working on a Kubernetes operator: https://github.com/goharbor/harbor-operator
I want to generate password for users.
Since users may choose their password, Harbor checks security level and requires 1 uppercase, 1 lowercase, 1 number and 1 special char. Otherwise it denies the password and I need to retry.

**Comment by sethvargo** [comment]
Got it - thanks for clarifying. I don't think we need a `/v2` - we can use git tags with Go modules. However, I think the current API is limiting and would like to change the _entire_ thing at once as a single breaking change. In short, instead of:

```go
Generate(var, var, var, var...)
```

I'd like to switch to:

```go
Generate(&GenerateConfig{
  Var: ...
  Var: ...
  Var: ...
})
```

What do you think? To be clear, I'm not asking you to do that work. I think it would provide flexibility for these types of enhancements in the future.

**Comment by holyhope** [comment]
It will be really great. Even more based on a interface

```go
interface {
    GetDigitsCount(context.Context) int32
    GetSpecialsCount(context.Context) int32
   ...
}
```

Probably with a `BasicGeneratorOption` with wrap it.

What do you think about something like

```go
type Pickup interface {
    // PickupSequence returns the slice on byte allowed for password generation,
    // and the number of bytes to pickup from this sequence
    PickupSequence(context.Context) ([]byte, int32, error)
}
```

So the `Generate()` function would look like:

```go
func Generate(ctx context.Context, pickups ...Pickup) ([]byte, error) {
    // TODO iterate over pickups and generate a mixed password from all sequences
}
```

Written with my phone, so I may be unclear, just let me know, I will rephrase it

**Comment by sethvargo** [comment]
Hey sorry - this was auto-closed when I renamed master -> main.

**Pull request closed without merging**
